# Generated by Django 4.0.4 on 2022-05-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_col_product_tagone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='col',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tagone',
        ),
    ]
