# Generated by Django 4.0.4 on 2022-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_col_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='e1',
            field=models.CharField(default='https://valtic.com.mx', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='e2',
            field=models.CharField(default='https://valtic.com.mx', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='e3',
            field=models.CharField(default='https://valtic.com.mx', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='e4',
            field=models.CharField(default='https://valtic.com.mx', max_length=50),
        ),
    ]
