# Generated by Django 4.0.4 on 2022-05-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('diametro', 'diametro'), ('rd', 'rd')], max_length=100),
        ),
    ]
