# Generated by Django 3.2.10 on 2022-08-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='e1',
            new_name='prod_catalogo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='e2',
            new_name='prod_ficha',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='e3',
            new_name='prod_precios',
        ),
    ]
