# Generated by Django 3.2.10 on 2022-08-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220825_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_fichas',
            new_name='prod_fich',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_precio',
            new_name='prod_pre',
        ),
    ]
