# Generated by Django 3.2.10 on 2022-09-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220825_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(choices=[('mineria', 'Mineria'), ('industrial', 'Industrial'), ('oil y gas', 'OPil y Gas'), ('energia', 'Energia'), ('agua potable', 'Agua potable'), ('agua residual', 'Agua Residual')], max_length=20)),
                ('img', models.CharField(blank=True, default='any', max_length=20)),
                ('col', models.CharField(blank=True, default='any', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
