# Generated by Django 3.2.10 on 2022-09-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_usos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usos',
        ),
    ]
