# Generated by Django 4.0.4 on 2022-05-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='CART',
            new_name='cart',
        ),
    ]
