# Generated by Django 4.0.4 on 2022-06-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
